title: Accessory Dwelling Unit
email: point85.llc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Plans for Accessory Dewelling Units (ADUs)
author: Kent Randall
baseurl: "/adu" # the subpath of the site
url: "" # the base hostname & protocol for the site

github_username:  point85

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag  
  
include:
  - images
  - docs
  - files
  
header_pages:
  - index.md
  - 1BR.md
  - 2BR.md
  - blog.md  
  - about.md  
